# Generated by Django 4.0.4 on 2022-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], max_length=100, null=True),
        ),
    ]
